#!/usr/bin/env bash
# agentic-core install.sh — 幂等物化脚本
#
# 用法：
#   git clone https://github.com/EW-00/agentic-core ~/workspace/core
#   cd ~/workspace/core && ./install.sh
#
# 选项：
#   --workspace DIR    workspace 位置（默认 $HOME/workspace）
#   --profile NAME     安装范围：client | firm | personal（默认 personal = 全量）
#                      清单：kernel/skills/PROFILES.txt 与 skills.txt 第三列
#   --no-third-party   跳过 skills.txt 第三方 skill 安装（离线/网络受限时）
#   --no-sentinel      不在 workspace 根创建哨兵 git repo
#   --copy-mode        用拷贝代替 symlink（Windows 原生侧自动启用）
#
# 幂等性约定：
#   - 只刷新自己生成的东西（带 generated 标记的 AGENTS.md、core-* 前缀的 rules、symlink）
#   - 永不覆盖：STUDY.md、study-*.md rules、projects/ 下任何内容、用户改过的 AGENTS.md
set -euo pipefail

CORE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE="$HOME/workspace"
PROFILE="personal"
THIRD_PARTY=1
SENTINEL=1
COPY_MODE=0

# Windsurf/Cursor 的全局 skills 目录：在对应机器上确认后回填（见 adapters/*/HANDBOOK.md）
WINDSURF_SKILLS_DIR="${WINDSURF_SKILLS_DIR:-}"
CURSOR_SKILLS_DIR="${CURSOR_SKILLS_DIR:-}"

while [ $# -gt 0 ]; do
  case "$1" in
    --workspace) WORKSPACE="$2"; shift 2 ;;
    --profile) PROFILE="$2"; shift 2 ;;
    --no-third-party) THIRD_PARTY=0; shift ;;
    --no-sentinel) SENTINEL=0; shift ;;
    --copy-mode) COPY_MODE=1; shift ;;
    *) echo "unknown option: $1" >&2; exit 1 ;;
  esac
done

case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*) COPY_MODE=1 ;;  # Windows 原生侧 symlink 不可靠
esac

GEN_MARK="generated by agentic-core install.sh"
say()  { printf '  \033[32m✓\033[0m %s\n' "$1"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$1"; }

link_or_copy() { # $1=src $2=dst  (目录或文件)
  if [ "$COPY_MODE" = 1 ]; then
    # 只覆盖本脚本自己拷出来的东西（带 marker），手工/其他工具的产物一律不碰
    if [ -e "$2" ] && [ ! -f "$2/.agentic-core-managed" ]; then
      warn "已存在且非本脚本产物，跳过：$2（确认无用可手动删除后重跑）"
      return 2
    fi
    rm -rf "$2"; cp -R "$1" "$2"; touch "$2/.agentic-core-managed" 2>/dev/null || true
  else
    # 目标是真目录/真文件（非 symlink）时不动它——ln -sfn 会把链接塞进目录内部制造嵌套垃圾
    if [ -e "$2" ] && [ ! -L "$2" ]; then
      warn "已存在且不是 symlink，跳过：$2（确认无用可手动删除后重跑）"
      return 2
    fi
    ln -sfn "$1" "$2"
  fi
}

case "$PROFILE" in client|firm|personal) ;; *) echo "invalid --profile: $PROFILE (client|firm|personal)" >&2; exit 1 ;; esac

# profile_match <profiles逗号串>：当前 profile 是否在标签里
profile_match() { case ",$1," in *",$PROFILE,"*) return 0 ;; *) return 1 ;; esac; }

echo "agentic-core install"
echo "  core:      $CORE_DIR"
echo "  workspace: $WORKSPACE"
echo "  profile:   $PROFILE"

# ---------------------------------------------------------------- workspace 骨架
mkdir -p "$WORKSPACE/projects"
say "workspace 骨架 (projects/)"

# ---------------------------------------------------------------- AGENTS.md
if [ ! -f "$WORKSPACE/AGENTS.md" ]; then
  cp "$CORE_DIR/templates/AGENTS.md.template" "$WORKSPACE/AGENTS.md"
  say "AGENTS.md 生成"
elif grep -q "$GEN_MARK" "$WORKSPACE/AGENTS.md"; then
  cp "$CORE_DIR/templates/AGENTS.md.template" "$WORKSPACE/AGENTS.md"
  say "AGENTS.md 刷新（含 generated 标记）"
else
  warn "AGENTS.md 已被手动修改，跳过（本机内容请移入 STUDY.md 后删掉该文件再重跑）"
fi

# ---------------------------------------------------------------- rules symlink
if link_or_copy "$CORE_DIR/kernel/rules" "$WORKSPACE/rules"; then
  say "rules/ → core/kernel/rules（SOUL/COMMUNICATION + axioms）"
fi
if [ ! -f "$CORE_DIR/kernel/rules/USER.md" ]; then
  warn "USER.md 未放置：它不入库（隐私），请手动放到 core/kernel/rules/USER.md（已被 .gitignore 忽略，见 Day-1 checklist）"
fi

# ---------------------------------------------------------------- STUDY.md（只创建一次）
if [ ! -f "$WORKSPACE/STUDY.md" ]; then
  cp "$CORE_DIR/templates/STUDY.md.template" "$WORKSPACE/STUDY.md"
  say "STUDY.md 模板就位 → 请填写"
else
  say "STUDY.md 已存在，不动"
fi

# ---------------------------------------------------------------- CLAUDE.md 入口统一
if [ ! -e "$WORKSPACE/CLAUDE.md" ]; then
  if [ "$COPY_MODE" = 1 ]; then cp "$WORKSPACE/AGENTS.md" "$WORKSPACE/CLAUDE.md";
  else ln -s "AGENTS.md" "$WORKSPACE/CLAUDE.md"; fi
  say "CLAUDE.md → AGENTS.md（Claude Code 入口）"
fi

# ---------------------------------------------------------------- vscode 设置（只创建一次）
if [ ! -f "$WORKSPACE/.vscode/settings.json" ]; then
  mkdir -p "$WORKSPACE/.vscode"
  cp "$CORE_DIR/templates/vscode-settings.json" "$WORKSPACE/.vscode/settings.json"
  say ".vscode/settings.json（SCM 降噪默认值）"
fi

# ---------------------------------------------------------------- Windsurf rules（只刷新 core-*）
mkdir -p "$WORKSPACE/.windsurf/rules"
for f in "$CORE_DIR"/adapters/windsurf/rules/core-*.md; do
  cp "$f" "$WORKSPACE/.windsurf/rules/$(basename "$f")"
done
say ".windsurf/rules/core-*.md 刷新（study-*.md 不受影响）"

# ---------------------------------------------------------------- 全局 skills
AGENTS_SKILLS="$HOME/.agents/skills"
mkdir -p "$AGENTS_SKILLS"

PROFILES_FILE="$CORE_DIR/kernel/skills/PROFILES.txt"
installed=0; skipped=0
for d in "$CORE_DIR"/kernel/skills/*/; do
  name="$(basename "$d")"
  tags="$(awk -v s="$name" '$1==s {print $2}' "$PROFILES_FILE" 2>/dev/null)"
  [ -z "$tags" ] && tags="personal"   # 未列入清单 → 默认只装个人机
  if profile_match "$tags"; then
    if link_or_copy "${d%/}" "$AGENTS_SKILLS/$name"; then
      installed=$((installed+1))
    fi
  else
    skipped=$((skipped+1))
  fi
done
say "kernel skills → ~/.agents/skills/（profile=$PROFILE：安装 $installed，按清单跳过 $skipped）"

if [ "$THIRD_PARTY" = 1 ]; then
  if command -v npx >/dev/null 2>&1; then
    while IFS= read -r line || [ -n "$line" ]; do
      case "$line" in ""|\#*) continue ;; esac
      set -- $line; repo="$1"; skill="$2"; tags="${3:-personal}"
      if ! profile_match "$tags"; then
        continue
      elif [ -e "$AGENTS_SKILLS/$skill" ]; then
        say "第三方 skill 已存在：$skill"
      else
        npx skills add "$repo" --skill "$skill" -g -y \
          && say "第三方 skill 安装：$skill" \
          || warn "第三方 skill 安装失败（网络受限？）：$skill —— 可稍后重跑"
      fi
    done < "$CORE_DIR/skills.txt"
  else
    warn "npx 不可用，跳过第三方 skills（装好 Node 后重跑，或 --no-third-party 静默）"
  fi
fi

# ---------------------------------------------------------------- 各工具接入全局 skills
ensure_tool_links() { # $1=工具 skills 目录
  mkdir -p "$1"
  for d in "$AGENTS_SKILLS"/*/; do
    name="$(basename "$d")"
    [ -e "$1/$name" ] || link_or_copy "${d%/}" "$1/$name" || true
  done
}
ensure_tool_links "$HOME/.claude/skills"
say "Claude Code 接入（~/.claude/skills/*）"
if [ -n "$WINDSURF_SKILLS_DIR" ]; then
  ensure_tool_links "$WINDSURF_SKILLS_DIR"; say "Windsurf 接入（$WINDSURF_SKILLS_DIR）"
else
  warn "WINDSURF_SKILLS_DIR 未设置——在 Windsurf 机器上确认全局 skills 目录后回填（见 adapters/windsurf/HANDBOOK.md §6）"
fi
if [ -n "$CURSOR_SKILLS_DIR" ]; then
  ensure_tool_links "$CURSOR_SKILLS_DIR"; say "Cursor 接入（$CURSOR_SKILLS_DIR）"
fi

# ---------------------------------------------------------------- 哨兵 root repo
if [ "$SENTINEL" = 1 ] && [ ! -d "$WORKSPACE/.git" ]; then
  git -C "$WORKSPACE" init -q
  echo '*' > "$WORKSPACE/.git/info/exclude"
  say "哨兵 root repo（.git/info/exclude='*'，无 .gitignore，永不 commit）"
fi
if [ -f "$WORKSPACE/.gitignore" ]; then
  warn "workspace 根发现 .gitignore —— Cascade 会因它拒改文件，规则应移入 .git/info/exclude（见 HANDBOOK §4）"
fi

echo
echo "完成。接下来："
echo "  1. 填写 $WORKSPACE/STUDY.md"
echo "  2. 把项目 repos clone 进 $WORKSPACE/projects/<study>/repos/"
echo "  3. 读一遍 core/adapters/<本机工具>/HANDBOOK.md"
